### ISSUE TITLE
Shop Link on Wiki is not working

### ISSUE THREAD

**Issue by m-r-m-s** [mzero/pulsar-buddy#2]
Hey hey - just a heads up that the shop link on the wiki is not working:
https://github.com/mzero/pulsar-buddy/wiki

"If you want to buy kits or fully assembled units from me, visit: https://show.electric.kitchen/"

**Comment by mzero** [comment]
Thanks for spotting that! Fixed.
The correct url is https://shop.electric.kitchen/

**Comment by m-r-m-s** [comment]
Sure thing!
